tags:
- Genki_1
- Lesson_7
- 02_Counting_People
vocabulary:
- tags:
  - counting_people
  vocabulary:
  - japanese: ひとり*
    english: one person
    kanji: 一人
  - japanese: ふたり*
    english: two people
    kanji: 二人
  - japanese: さんにん
    english: three people
    kanji: 三人
  - japanese: よにん*
    english: four people
    kanji: 四人
  - japanese: ごにん
    english: five people
    kanji: 五人
  - japanese: ろくにん
    english: six people
    kanji: 六人
  - japanese: しちにん／ななにん
    english: seven people
    kanji: 七人
  - japanese: はちにん
    english: eight people
    kanji: 八人
  - japanese: きゅうにん
    english: nine people
    kanji: 九人
  - japanese: じゅうにん
    english: ten people
    kanji: 十人
