tags:
- Genki_1
- Lesson_7
- 03_Bodyparts
vocabulary:
- tags:
  - Useful_Expressions
  vocabulary:
  - japanese: かみ
    english: hair
    kanji: 髪
  - japanese: くち
    english: mouth
    kanji: 口
  - japanese: め
    english: eye
    kanji: 目
  - japanese: はな
    english: nose
    kanji: 鼻
  - japanese: ゆび
    english: finger
    kanji: 指
  - japanese: は
    english: tooth
    kanji: 歯
  - japanese: まゆげ
    english: eyebrows
    kanji: 眉毛
  - japanese: みみ
    english: ear
    kanji: 耳
  - japanese: て
    english: hand
    kanji: 手
  - japanese: くび
    english: neck
    kanji: 首
  - japanese: あたま
    english: head
    kanji: 頭
  - japanese: せなか
    english: back
    kanji: 背中
  - japanese: おしり
    english: buttocks
  - japanese: かお
    english: face
    kanji: 顔
  - japanese: かた
    english: shoulder
    kanji: 肩
  - japanese: むね
    english: breast
    kanji: 胸
  - japanese: おなか
    english: stomach
  - japanese: あし
    english: leg; foot
    kanji: 足
