tags:
- Genki_1
- Lesson_9
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: たんご
    english: word; vocabulary
    kanji: 単語
    sound_file: Kaiwa_Bunpo_L09/K09_07/3.mp3
  - japanese: さくぶん
    english: essay; composition
    kanji: 作文
    sound_file: Kaiwa_Bunpo_L09/K09_07/6.mp3
  - japanese: しけん
    english: exam
    kanji: 試験
    sound_file: Kaiwa_Bunpo_L09/K09_07/9.mp3
  - japanese: てがみ
    english: letter
    kanji: 手紙
    sound_file: Kaiwa_Bunpo_L09/K09_07/11.mp3
  - japanese: メール
    english: e-mail
    sound_file: Kaiwa_Bunpo_L09/K09_07/13.mp3
  - japanese: ギター
    english: guitar
    sound_file: Kaiwa_Bunpo_L09/K09_07/15.mp3
  - japanese: ピアノ
    english: piano
    sound_file: Kaiwa_Bunpo_L09/K09_07/17.mp3
  - japanese: コンサート
    english: concert
    sound_file: Kaiwa_Bunpo_L09/K09_07/19.mp3
  - japanese: チケット
    english: ticket
    sound_file: Kaiwa_Bunpo_L09/K09_07/21.mp3
  - japanese: かぶき
    english: Kabuki; traditional Japanese theatrical art
    kanji: 歌舞伎
    sound_file: Kaiwa_Bunpo_L09/K09_07/23.mp3
  - japanese: スキー
    english: ski
    sound_file: Kaiwa_Bunpo_L09/K09_07/26.mp3
  - japanese: おべんとう
    english: boxed lunch
    kanji: お弁当
    sound_file: Kaiwa_Bunpo_L09/K09_07/28.mp3
  - japanese: ピザ
    english: pizza
    sound_file: Kaiwa_Bunpo_L09/K09_07/30.mp3
  - japanese: びょうき
    english: illness; sickness
    kanji: 病気
    sound_file: Kaiwa_Bunpo_L09/K09_07/32.mp3
  - japanese: くすり
    english: medicine
    kanji: 薬
    sound_file: Kaiwa_Bunpo_L09/K09_07/35.mp3
  - japanese: いいこ
    english: good child
    kanji: いい子
    sound_file: Kaiwa_Bunpo_L09/K09_07/37.mp3
  - japanese: いろ
    english: color
    kanji: 色
    sound_file: Kaiwa_Bunpo_L09/K09_07/39.mp3
  - japanese: こんど
    english: near future
    kanji: 今度
    sound_file: Kaiwa_Bunpo_L09/K09_07/41.mp3
  - japanese: せんげつ
    english: last month
    kanji: 先月
    sound_file: Kaiwa_Bunpo_L09/K09_07/43.mp3
  - japanese: きょねん
    english: last year
    kanji: 去年
    sound_file: Kaiwa_Bunpo_L09/K09_07/45.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: あおい
    english: blue
    kanji: 青い
    sound_file: Kaiwa_Bunpo_L09/K09_07/48.mp3
  - japanese: あかい
    english: red
    kanji: 赤い
    sound_file: Kaiwa_Bunpo_L09/K09_07/50.mp3
  - japanese: くろい
    english: black
    kanji: 黒い
    sound_file: Kaiwa_Bunpo_L09/K09_07/52.mp3
  - japanese: しろい
    english: white
    kanji: 白い
    sound_file: Kaiwa_Bunpo_L09/K09_07/54.mp3
  - japanese: さびしい
    english: lonely
    kanji: 寂しい
    sound_file: Kaiwa_Bunpo_L09/K09_07/56.mp3
  - japanese: わかい
    english: young
    kanji: 若い
    sound_file: Kaiwa_Bunpo_L09/K09_07/58.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: いじわる（な）
    english: mean-spirited
    kanji: 意地悪
    sound_file: Kaiwa_Bunpo_L09/K09_07/61.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: おどる
    english: to dance
    kanji: 踊る
    sound_file: Kaiwa_Bunpo_L09/K09_07/64.mp3
  - japanese: おわる
    english: (something) ends (〜が)
    kanji: 終わる
    sound_file: Kaiwa_Bunpo_L09/K09_07/66.mp3
  - japanese: くすりをのむ
    english: to take medicine
    kanji: 薬を飲む
    sound_file: Kaiwa_Bunpo_L09/K09_07/68.mp3
  - japanese: にんきがある
    english: to be popular
    kanji: 人気がある
    sound_file: Kaiwa_Bunpo_L09/K09_07/70.mp3
  - japanese: はじまる
    english: (something) begins (〜が)
    kanji: 始まる
    sound_file: Kaiwa_Bunpo_L09/K09_07/72.mp3
  - japanese: ひく
    english: to play (a string instrument or piano) (〜を)
    kanji: 弾く
    sound_file: Kaiwa_Bunpo_L09/K09_07/74.mp3
  - japanese: もらう
    english: to get (from somebody) (<i>person</i> に <i>thing</i> を)
    sound_file: Kaiwa_Bunpo_L09/K09_07/76.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: おぼえる
    english: to memorize (〜を)
    kanji: 覚える
    sound_file: Kaiwa_Bunpo_L09/K09_07/79.mp3
  - japanese: でる
    english: (1) to appear; to attend (〜に)<div>(2) to exit (〜を)</div>
    kanji: 出る
    sound_file: Kaiwa_Bunpo_L09/K09_07/81.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: うんどうする
    english: to exercise
    kanji: 運動する
    sound_file: Kaiwa_Bunpo_L09/K09_07/86.mp3
  - japanese: さんぽする
    english: to take a walk
    kanji: 散歩する
    sound_file: Kaiwa_Bunpo_L09/K09_07/88.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: そう
    english: (I think) so
    sound_file: Kaiwa_Bunpo_L09/K09_07/91.mp3
  - japanese: 〜から
    english: from ...
    sound_file: Kaiwa_Bunpo_L09/K09_07/93.mp3
  - japanese: 〜まで
    english: to (a place/a time)
    sound_file: Kaiwa_Bunpo_L09/K09_07/95.mp3
  - japanese: ぜひ
    english: by all means
    kanji: 是非
    sound_file: Kaiwa_Bunpo_L09/K09_07/97.mp3
  - japanese: ところで
    english: by the way
    sound_file: Kaiwa_Bunpo_L09/K09_07/99.mp3
  - japanese: みんな
    english: all
    sound_file: Kaiwa_Bunpo_L09/K09_07/101.mp3
  - japanese: もう
    english: already
    sound_file: Kaiwa_Bunpo_L09/K09_07/103.mp3
- tags:
  - Numbers
  vocabulary:
  - japanese: ひとつ
    english: one - counter for small objects
    kanji: 一つ
    sound_file: Kaiwa_Bunpo_L09/K09_07/106.mp3
  - japanese: ふたつ
    english: two - counter for small objects
    kanji: 二つ
    sound_file: Kaiwa_Bunpo_L09/K09_07/108.mp3
  - japanese: みっつ
    english: three - counter for small objects
    kanji: 三つ
    sound_file: Kaiwa_Bunpo_L09/K09_07/110.mp3
  - japanese: よっつ
    english: four - counter for small objects
    kanji: 四つ
    sound_file: Kaiwa_Bunpo_L09/K09_07/112.mp3
  - japanese: いつつ
    english: five - counter for small objects
    kanji: 五つ
    sound_file: Kaiwa_Bunpo_L09/K09_07/114.mp3
  - japanese: むっつ
    english: six - counter for small objects
    kanji: 六つ
    sound_file: Kaiwa_Bunpo_L09/K09_07/116.mp3
  - japanese: ななつ
    english: seven - counter for small objects
    kanji: 七つ
    sound_file: Kaiwa_Bunpo_L09/K09_07/118.mp3
  - japanese: やっつ
    english: eight - counter for small objects
    kanji: 八つ
    sound_file: Kaiwa_Bunpo_L09/K09_07/120.mp3
  - japanese: ここのつ
    english: nine - counter for small objects
    kanji: 九つ
    sound_file: Kaiwa_Bunpo_L09/K09_07/122.mp3
  - japanese: とお
    english: ten - counter for small objects
    kanji: 十
    sound_file: Kaiwa_Bunpo_L09/K09_07/124.mp3
