tags:
- Genki_1
- Lesson_9
- 02_Colors
vocabulary:
- tags:
  - Useful_Expressions
  vocabulary:
  - japanese: くろい
    english: black
    kanji: 黒い
  - japanese: しろい
    english: white
    kanji: 白い
  - japanese: あかい
    english: red
    kanji: 赤い
  - japanese: あおい
    english: blue
    kanji: 青い
  - japanese: きいろい
    english: yellow
    kanji: 黄色い
  - japanese: ちゃいろい
    english: brown
    kanji: 茶色い
  - japanese: みどり／グリーン
    english: green
    kanji: 緑
  - japanese: こんいろ
    english: navy blue
    kanji: 紺色
  - japanese: みずいろ
    english: light blue
    kanji: 水色
  - japanese: ぎんいろ／シルバー
    english: silver
    kanji: 銀色
  - japanese: オレンジ
    english: orange
  - japanese: むらさき
    english: purple
    kanji: 紫
  - japanese: はいいろ／グレー
    english: gray
    kanji: 灰色
  - japanese: きんいろ／ゴールド
    english: gold
    kanji: 金色
  - japanese: ピンク
    english: pink
  - japanese: ベージュ
    english: beige
  - japanese: かおがあおいですね。
    english: You look pale.
    kanji: 顔が青いですね。
  - japanese: しろくろのしゃしん
    english: black and white picture
    kanji: 白黒の写真
  - japanese: あおしんごう
    english: green light
    kanji: 青信号
