tags:
- Genki_1
- Lesson_0
- 01_Greetings
vocabulary:
- tags:
  - L1_Greetings
  vocabulary:
  - japanese: おはよう。
    english: Good morning.
    sound_file: Kaiwa_Bunpo_L00/K00_01/1.mp3
  - japanese: おはよう　ございます。
    english: Good morning. (polite)
    sound_file: Kaiwa_Bunpo_L00/K00_01/3.mp3
  - japanese: こんにちは。
    english: Good afternoon.
    sound_file: Kaiwa_Bunpo_L00/K00_01/5.mp3
  - japanese: こんばんは。
    english: Good evening.
    sound_file: Kaiwa_Bunpo_L00/K00_01/7.mp3
  - japanese: さようなら。
    english: Good-bye.
    sound_file: Kaiwa_Bunpo_L00/K00_01/9.mp3
  - japanese: おやすみ（なさい）。
    english: Good night.
    sound_file: Kaiwa_Bunpo_L00/K00_01/11.mp3
  - japanese: ありがとう。
    english: Thank you.
    sound_file: Kaiwa_Bunpo_L00/K00_01/13.mp3
  - japanese: ありがとう　ございます。
    english: Thank you. (polite)
    sound_file: Kaiwa_Bunpo_L00/K00_01/15.mp3
  - japanese: すみません。
    english: Excuse me.; I'm sorry.
    sound_file: Kaiwa_Bunpo_L00/K00_01/17.mp3
  - japanese: いいえ。
    english: No.; Not at all.
    sound_file: Kaiwa_Bunpo_L00/K00_01/20.mp3
  - japanese: いってきます。
    english: I'll go and come back.
    sound_file: Kaiwa_Bunpo_L00/K00_01/22.mp3
  - japanese: いってらっしゃい。
    english: Please go and come back.
    sound_file: Kaiwa_Bunpo_L00/K00_01/24.mp3
  - japanese: ただいま。
    english: I'm home.
    sound_file: Kaiwa_Bunpo_L00/K00_01/26.mp3
  - japanese: おかえり（なさい）。
    english: Welcome home.
    sound_file: Kaiwa_Bunpo_L00/K00_01/28.mp3
  - japanese: いただきます。
    english: Thank you for the meal. (before eating)
    sound_file: Kaiwa_Bunpo_L00/K00_01/30.mp3
  - japanese: ごちそうさま（でした）。
    english: Thank you for the meal. (after eating)
    sound_file: Kaiwa_Bunpo_L00/K00_01/32.mp3
  - japanese: はじめまして。
    english: How do you do?
    sound_file: Kaiwa_Bunpo_L00/K00_01/34.mp3
  - japanese: 〜です。
    english: I am ...
    sound_file: Kaiwa_Bunpo_L00/K00_01/36.mp3
  - japanese: よろしく　おねがいします。
    english: Nice to meet you.
    sound_file: Kaiwa_Bunpo_L00/K00_01/38.mp3
