tags:
- Genki_1
- Lesson_0
- 02_Numbers_0-100
vocabulary:
- tags:
  - L1_Numbers
  vocabulary:
  - japanese: ゼロ／れい
    english: '0'
    sound_file: Kaiwa_Bunpo_L00/K00_02/1.mp3
  - japanese: いち
    english: '1'
    kanji: 一
    sound_file: Kaiwa_Bunpo_L00/K00_02/2.mp3
  - japanese: に
    english: '2'
    kanji: 二
    sound_file: Kaiwa_Bunpo_L00/K00_02/3.mp3
  - japanese: さん
    english: '3'
    kanji: 三
    sound_file: Kaiwa_Bunpo_L00/K00_02/4.mp3
  - japanese: よん／し／（よ）
    english: '4'
    kanji: 四
    sound_file: Kaiwa_Bunpo_L00/K00_02/5.mp3
  - japanese: ご
    english: '5'
    kanji: 五
    sound_file: Kaiwa_Bunpo_L00/K00_02/6.mp3
  - japanese: ろく
    english: '6'
    kanji: 六
    sound_file: Kaiwa_Bunpo_L00/K00_02/7.mp3
  - japanese: なな／しち
    english: '7'
    kanji: 七
    sound_file: Kaiwa_Bunpo_L00/K00_02/8.mp3
  - japanese: はち
    english: '8'
    kanji: 八
    sound_file: Kaiwa_Bunpo_L00/K00_02/9.mp3
  - japanese: きゅう／く
    english: '9'
    kanji: 九
    sound_file: Kaiwa_Bunpo_L00/K00_02/10.mp3
  - japanese: じゅう
    english: '10'
    kanji: 十
    sound_file: Kaiwa_Bunpo_L00/K00_02/11.mp3
  - japanese: じゅういち
    english: '11'
    kanji: 十一
    sound_file: Kaiwa_Bunpo_L00/K00_02/12.mp3
  - japanese: じゅうに
    english: '12'
    kanji: 十二
    sound_file: Kaiwa_Bunpo_L00/K00_02/13.mp3
  - japanese: じゅうさん
    english: '13'
    kanji: 十三
    sound_file: Kaiwa_Bunpo_L00/K00_02/14.mp3
  - japanese: じゅうよん／じゅうし
    english: '14'
    kanji: 十四
    sound_file: Kaiwa_Bunpo_L00/K00_02/15.mp3
  - japanese: じゅうご
    english: '15'
    kanji: 十五
    sound_file: Kaiwa_Bunpo_L00/K00_02/16.mp3
  - japanese: じゅうろく
    english: '16'
    kanji: 十六
    sound_file: Kaiwa_Bunpo_L00/K00_02/17.mp3
  - japanese: じゅうなな／じゅうしち
    english: '17'
    kanji: 十七
    sound_file: Kaiwa_Bunpo_L00/K00_02/18.mp3
  - japanese: じゅうはち
    english: '18'
    kanji: 十八
    sound_file: Kaiwa_Bunpo_L00/K00_02/19.mp3
  - japanese: じゅうきゅう／じゅうく
    english: '19'
    kanji: 十九
    sound_file: Kaiwa_Bunpo_L00/K00_02/20.mp3
  - japanese: にじゅう
    english: '20'
    kanji: 二十
    sound_file: Kaiwa_Bunpo_L00/K00_02/21.mp3
  - japanese: さんじゅう
    english: '30'
    kanji: 三十
    sound_file: Kaiwa_Bunpo_L00/K00_02/22.mp3
  - japanese: よんじゅう
    english: '40'
    kanji: 四十
    sound_file: Kaiwa_Bunpo_L00/K00_02/23.mp3
  - japanese: ごじゅう
    english: '50'
    kanji: 五十
    sound_file: Kaiwa_Bunpo_L00/K00_02/24.mp3
  - japanese: ろくじゅう
    english: '60'
    kanji: 六十
    sound_file: Kaiwa_Bunpo_L00/K00_02/25.mp3
  - japanese: ななじゅう
    english: '70'
    kanji: 七十
    sound_file: Kaiwa_Bunpo_L00/K00_02/26.mp3
  - japanese: はちじゅう
    english: '80'
    kanji: 八十
    sound_file: Kaiwa_Bunpo_L00/K00_02/27.mp3
  - japanese: きゅうじゅう
    english: '90'
    kanji: 九十
    sound_file: Kaiwa_Bunpo_L00/K00_02/28.mp3
  - japanese: ひゃく
    english: '100'
    kanji: 百
    sound_file: Kaiwa_Bunpo_L00/K00_02/29.mp3
