tags:
- Genki_2
- Lesson_20
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: アニメ
    english: animation
    sound_file: Kaiwa_Bunpo_L20/K20_05/3.mp3
  - japanese: しょうせつ
    english: novel
    kanji: 小説
    sound_file: Kaiwa_Bunpo_L20/K20_05/5.mp3
  - japanese: しゅみ
    english: hobby; pastime
    kanji: 趣味
    sound_file: Kaiwa_Bunpo_L20/K20_05/7.mp3
  - japanese: つき
    english: moon
    kanji: 月
    sound_file: Kaiwa_Bunpo_L20/K20_05/9.mp3
  - japanese: うちゅうじん
    english: space alien
    kanji: 宇宙人
    sound_file: Kaiwa_Bunpo_L20/K20_05/11.mp3
  - japanese: せんす
    english: (hand) fan
    kanji: 扇子
    sound_file: Kaiwa_Bunpo_L20/K20_05/13.mp3
  - japanese: スニーカー
    english: sneakers
    sound_file: Kaiwa_Bunpo_L20/K20_05/15.mp3
  - japanese: ヘッドホン
    english: headphones
    sound_file: Kaiwa_Bunpo_L20/K20_05/17.mp3
  - japanese: おにぎり
    english: rice ball
    kanji: お握り（rare）
    sound_file: Kaiwa_Bunpo_L20/K20_05/19.mp3
  - japanese: どうぶつ
    english: animal
    kanji: 動物
    sound_file: Kaiwa_Bunpo_L20/K20_05/21.mp3
  - japanese: あちら
    english: that way (polite)
    kanji: 彼方（rare）
    sound_file: Kaiwa_Bunpo_L20/K20_05/23.mp3
  - japanese: かかりのもの
    english: our person in charge
    kanji: 係りの者
    sound_file: Kaiwa_Bunpo_L20/K20_05/25.mp3
  - japanese: おたく
    english: (someone's) home/house
    kanji: お宅
    sound_file: Kaiwa_Bunpo_L20/K20_05/27.mp3
  - japanese: ～や
    english: …shop
    kanji: ～屋
    sound_file: Kaiwa_Bunpo_L20/K20_05/29.mp3
  - japanese: してん
    english: branch office
    kanji: 支店
    sound_file: Kaiwa_Bunpo_L20/K20_05/31.mp3
  - japanese: ドイツ
    english: Germany
    kanji: 独逸（rare）
    sound_file: Kaiwa_Bunpo_L20/K20_05/33.mp3
  - japanese: しんごう
    english: traffic light
    kanji: 信号
    sound_file: Kaiwa_Bunpo_L20/K20_05/35.mp3
  - japanese: かど
    english: corner
    kanji: 角
    sound_file: Kaiwa_Bunpo_L20/K20_05/37.mp3
  - japanese: じ
    english: letter; character
    kanji: 字
    sound_file: Kaiwa_Bunpo_L20/K20_05/39.mp3
  - japanese: おと
    english: sound
    kanji: 音
    sound_file: Kaiwa_Bunpo_L20/K20_05/41.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: おもい
    english: heavy; serious (illness)
    kanji: 重い
    sound_file: Kaiwa_Bunpo_L20/K20_05/43.mp3
  - japanese: かるい
    english: light
    kanji: 軽い
    sound_file: Kaiwa_Bunpo_L20/K20_05/45.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: ふしぎ(な)
    english: mysterious
    kanji: 不思議
    sound_file: Kaiwa_Bunpo_L20/K20_05/47.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: おる
    english: extra-modest expression for いる
    kanji: 居る（rare）
    sound_file: Kaiwa_Bunpo_L20/K20_05/49.mp3
  - japanese: まいる
    english: extra-modest expression for いく、くる
    kanji: 参る
    sound_file: Kaiwa_Bunpo_L20/K20_05/51.mp3
  - japanese: もうす
    english: extra-modest expression for いう
    kanji: 申す
    sound_file: Kaiwa_Bunpo_L20/K20_05/53.mp3
  - japanese: いたす
    english: extra-modest expression for する
    kanji: 致す
    sound_file: Kaiwa_Bunpo_L20/K20_05/56.mp3
  - japanese: いただく
    english: extra-modest expression for たべる、のむ
    kanji: 頂く
    sound_file: Kaiwa_Bunpo_L20/K20_05/58.mp3
  - japanese: ござる
    english: extra-modest expression for ある
    kanji: 御座る
    sound_file: Kaiwa_Bunpo_L20/K20_05/60.mp3
  - japanese: ～ておる
    english: extra-modest expression for ～ている
    kanji: ～て居る（rare）
    sound_file: Kaiwa_Bunpo_L20/K20_05/62.mp3
  - japanese: ～でござる
    english: extra-modest expression for です
    kanji: ～御座る（rare）
    sound_file: Kaiwa_Bunpo_L20/K20_05/64.mp3
  - japanese: いただく
    english: humble expression for もらう
    kanji: 頂く
    sound_file: Kaiwa_Bunpo_L20/K20_05/66.mp3
  - japanese: うかがう
    english: (1) to humbly visit (place に); to humbly ask (person に)
    kanji: 伺う
    sound_file: Kaiwa_Bunpo_L20/K20_05/68.mp3
  - japanese: まがる
    english: to turn (right/left) (corner を direction に)
    kanji: 曲がる
    sound_file: Kaiwa_Bunpo_L20/K20_05/70.mp3
  - japanese: もどる
    english: to return; to come back (～に)
    kanji: 戻る
    sound_file: Kaiwa_Bunpo_L20/K20_05/72.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: さしあげる
    english: humble expression for あげる
    kanji: 差し上げる
    sound_file: Kaiwa_Bunpo_L20/K20_05/74.mp3
  - japanese: きこえる
    english: to be audible (～が)
    kanji: 聞こえる
    sound_file: Kaiwa_Bunpo_L20/K20_05/76.mp3
  - japanese: つたえる
    english: to convey message (person に)
    kanji: 伝える
    sound_file: Kaiwa_Bunpo_L20/K20_05/78.mp3
  - japanese: またせる
    english: to keep (someone) waiting (～を)
    kanji: 待たせる
    sound_file: Kaiwa_Bunpo_L20/K20_05/81.mp3
  - japanese: つづける
    english: to continue (～を)
    kanji: 続ける
    sound_file: Kaiwa_Bunpo_L20/K20_05/83.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: こうかんする
    english: to exchange (XとYを)
    kanji: 交換する
    sound_file: Kaiwa_Bunpo_L20/K20_05/86.mp3
  - japanese: へんぴんする
    english: to return (merchandise) (～を)
    kanji: 返品する
    sound_file: Kaiwa_Bunpo_L20/K20_05/88.mp3
  - japanese: せいかつする
    english: to lead a life
    kanji: 生活する
    sound_file: Kaiwa_Bunpo_L20/K20_05/91.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: ～かい
    english: …th floor
    kanji: ～階
    sound_file: Kaiwa_Bunpo_L20/K20_05/93.mp3
  - japanese: いっかい
    english: first floor
    kanji: 一階
    sound_file: Kaiwa_Bunpo_L20/K20_05/96.mp3
  - japanese: ～みたいなX
    english: X like …
    sound_file: Kaiwa_Bunpo_L20/K20_05/98.mp3
  - japanese: また
    english: again
    kanji: 又（rare）
    sound_file: Kaiwa_Bunpo_L20/K20_05/101.mp3
  - japanese: では
    english: well then (polite)
    sound_file: Kaiwa_Bunpo_L20/K20_05/103.mp3
  - japanese: できれば
    english: if possible
    kanji: 出来れば（rare）
    sound_file: Kaiwa_Bunpo_L20/K20_05/105.mp3
  - japanese: まことに
    english: really (very polite)
    kanji: 誠に
    sound_file: Kaiwa_Bunpo_L20/K20_05/107.mp3
  - japanese: よろしかったら
    english: if it is okay (polite)
    kanji: 宜しかったら
    sound_file: Kaiwa_Bunpo_L20/K20_05/109.mp3
  - japanese: かしこまりました
    english: certainly
    kanji: 畏まりました（rare）
    sound_file: Kaiwa_Bunpo_L20/K20_05/111.mp3
  - japanese: しつれいしました
    english: I'm very sorry
    kanji: 失礼しました
    sound_file: Kaiwa_Bunpo_L20/K20_05/113.mp3
  - japanese: もうしわけありません
    english: You have my apologies (polite)
    kanji: 申し訳ありません
    sound_file: Kaiwa_Bunpo_L20/K20_05/115.mp3
