tags:
- Genki_1
- Lesson_12
- 02_Health_And_Illness
vocabulary:
- tags:
  - Useful_Expressions
  vocabulary:
  - japanese: げりです。
    english: I have diarrhea.
    kanji: 下痢です。
  - japanese: べんぴです。
    english: I am constipated.
    kanji: 便秘です。
  - japanese: せいりです。
    english: I have my period.
    kanji: 生理です。
  - japanese: かふんしょうです。
    english: I have hay fever.
    kanji: 花粉症です。
  - japanese: （〜に）アレルギーがあります。
    english: I have an allergy to ...
  - japanese: むしばがあります。
    english: I have a bad tooth.
    kanji: 虫歯があります。
  - japanese: くしゃみがでます。
    english: I sneeze.
    kanji: くしゃみが出ます。
  - japanese: はなみずがでます。
    english: I have a runny nose.
    kanji: 鼻水が出ます。
  - japanese: せなかがかゆいです。
    english: My back itches.
    kanji: 背中がかゆいです。
  - japanese: はっしんがあります。
    english: I have rashes.
    kanji: 発疹があります。
  - japanese: めまいがします。
    english: I feel dizzy.
  - japanese: はきました。
    english: I threw up.
    kanji: 吐きました。
  - japanese: きぶんがわるいです。
    english: I am not feeling well.
    kanji: 気分が悪いです。
  - japanese: やけどをしました。
    english: I burned myself.
  - japanese: あしをこっせつしました。
    english: I broke my leg.
    kanji: 足を骨折しました。
  - japanese: けがをしました。
    english: I hurt myself.
  - japanese: ないか
    english: physician
    kanji: 内科
  - japanese: ひふか
    english: dermatologist
    kanji: 皮膚科
  - japanese: げか
    english: surgeon
    kanji: 外科
  - japanese: さんふじんか
    english: obsterician and gynecologist
    kanji: 産婦人科
  - japanese: せいけいげか
    english: orthopedic surgeon
    kanji: 整形外科
  - japanese: がんか（めいしゃ）
    english: ophthalmologist
    kanji: 眼科（目医者）
  - japanese: しか（はいしゃ）
    english: dentist
    kanji: 歯科（歯医者）
  - japanese: じびか
    english: otorhinolaryngologist; ENT doctor
    kanji: 耳鼻科
  - japanese: こうせいぶっしつ
    english: antibiotic
    kanji: 抗生物質
  - japanese: レントゲン
    english: X-ray
  - japanese: しゅじゅつ
    english: operation
    kanji: 手術
  - japanese: ちゅうしゃ
    english: injection
    kanji: 注射
  - japanese: たいおんけい
    english: thermometer
    kanji: 体温計
  - japanese: てんてき
    english: intravenous feeding
    kanji: 点滴
