tags:
- Genki_1
- Lesson_3
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - tags:
    - Entertainment_and_Sports
    vocabulary:
    - japanese: えいが
      english: movie
      kanji: 映画
      sound_file: Kaiwa_Bunpo_L03/K03_05/4.mp3
    - japanese: おんがく
      english: music
      kanji: 音楽
      sound_file: Kaiwa_Bunpo_L03/K03_05/6.mp3
    - japanese: ざっし
      english: magazine
      kanji: 雑誌
      sound_file: Kaiwa_Bunpo_L03/K03_05/8.mp3
    - japanese: スポーツ
      english: sports
      sound_file: Kaiwa_Bunpo_L03/K03_05/10.mp3
    - japanese: デート
      english: date (romantic, not calendar)
      sound_file: Kaiwa_Bunpo_L03/K03_05/12.mp3
    - japanese: テニス
      english: tennis
      sound_file: Kaiwa_Bunpo_L03/K03_05/14.mp3
    - japanese: テレビ
      english: TV
      sound_file: Kaiwa_Bunpo_L03/K03_05/16.mp3
  - tags:
    - Foods_and_Drinks
    vocabulary:
    - japanese: アイスクリーム
      english: ice cream
      sound_file: Kaiwa_Bunpo_L03/K03_05/18.mp3
    - japanese: ハンバーガー
      english: hamburger
      sound_file: Kaiwa_Bunpo_L03/K03_05/20.mp3
    - japanese: おさけ
      english: sake; alcoholic drink
      kanji: お酒
      sound_file: Kaiwa_Bunpo_L03/K03_05/22.mp3
    - japanese: おちゃ
      english: green tea
      kanji: お茶
      sound_file: Kaiwa_Bunpo_L03/K03_05/24.mp3
    - japanese: コーヒー
      english: coffee
      sound_file: Kaiwa_Bunpo_L03/K03_05/26.mp3
    - japanese: みず
      english: water
      kanji: 水
      sound_file: Kaiwa_Bunpo_L03/K03_05/28.mp3
    - japanese: あさごはん
      english: breakfast
      kanji: 朝ご飯
      sound_file: Kaiwa_Bunpo_L03/K03_05/30.mp3
    - japanese: ひるごはん
      english: lunch
      kanji: 昼ご飯
      sound_file: Kaiwa_Bunpo_L03/K03_05/33.mp3
    - japanese: ばんごはん
      english: dinner
      kanji: 晩ご飯
      sound_file: Kaiwa_Bunpo_L03/K03_05/35.mp3
  - tags:
    - Places
    vocabulary:
    - japanese: いえ
      english: home; house
      kanji: 家
      sound_file: Kaiwa_Bunpo_L03/K03_05/37.mp3
    - japanese: うち
      english: home; house; my place
      sound_file: Kaiwa_Bunpo_L03/K03_05/39.mp3
    - japanese: がっこう
      english: school
      kanji: 学校
      sound_file: Kaiwa_Bunpo_L03/K03_05/41.mp3
    - japanese: カフェ
      english: cafe
      sound_file: Kaiwa_Bunpo_L03/K03_05/43.mp3
  - tags:
    - Time
    vocabulary:
    - japanese: あした
      english: tomorrow
      kanji: 明日
      sound_file: Kaiwa_Bunpo_L03/K03_05/46.mp3
    - japanese: きょう
      english: today
      kanji: 今日
      sound_file: Kaiwa_Bunpo_L03/K03_05/48.mp3
    - japanese: あさ
      english: morning
      kanji: 朝
      sound_file: Kaiwa_Bunpo_L03/K03_05/50.mp3
    - japanese: こんばん
      english: tonight
      kanji: 今晩
      sound_file: Kaiwa_Bunpo_L03/K03_05/52.mp3
    - japanese: まいにち
      english: every day
      kanji: 毎日
      sound_file: Kaiwa_Bunpo_L03/K03_05/54.mp3
    - japanese: まいばん
      english: every night
      kanji: 毎晩
      sound_file: Kaiwa_Bunpo_L03/K03_05/56.mp3
    - japanese: しゅうまつ
      english: weekend
      kanji: 週末
      sound_file: Kaiwa_Bunpo_L03/K03_05/58.mp3
    - japanese: どようび
      english: Saturday
      kanji: 土曜日
      sound_file: Kaiwa_Bunpo_L03/K03_05/60.mp3
    - japanese: にちようび
      english: Sunday
      kanji: 日曜日
      sound_file: Kaiwa_Bunpo_L03/K03_05/62.mp3
    - japanese: いつ
      english: when
      sound_file: Kaiwa_Bunpo_L03/K03_05/64.mp3
    - japanese: 〜ごろ
      english: at about ...
      sound_file: Kaiwa_Bunpo_L03/K03_05/66.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: いく
    english: to go (<i>destination</i> に/へ)
    kanji: 行く
    sound_file: Kaiwa_Bunpo_L03/K03_05/68.mp3
  - japanese: かえる
    english: to go back; to return (<i>destination</i> に/へ)
    kanji: 帰る
    sound_file: Kaiwa_Bunpo_L03/K03_05/71.mp3
  - japanese: きく
    english: to listen; to hear (〜を); to ask (<i>person</i>&nbsp;に)
    kanji: 聞く
    sound_file: Kaiwa_Bunpo_L03/K03_05/73.mp3
  - japanese: のむ
    english: to drink (〜を)
    kanji: 飲む
    sound_file: Kaiwa_Bunpo_L03/K03_05/76.mp3
  - japanese: はなす
    english: to speak; to talk (<i>language</i> を/で)
    kanji: 話す
    sound_file: Kaiwa_Bunpo_L03/K03_05/78.mp3
  - japanese: よむ
    english: to read (〜を)
    kanji: 読む
    sound_file: Kaiwa_Bunpo_L03/K03_05/82.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: おきる
    english: to get up
    kanji: 起きる
    sound_file: Kaiwa_Bunpo_L03/K03_05/84.mp3
  - japanese: たべる
    english: to eat (〜を)
    kanji: 食べる
    sound_file: Kaiwa_Bunpo_L03/K03_05/86.mp3
  - japanese: ねる
    english: to sleep; to go to sleep
    kanji: 寝る
    sound_file: Kaiwa_Bunpo_L03/K03_05/88.mp3
  - japanese: みる
    english: to see; to look at; to watch (〜を)
    kanji: 見る
    sound_file: Kaiwa_Bunpo_L03/K03_05/91.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: くる
    english: to come (<i>destination</i> に/へ)
    kanji: 来る
    sound_file: Kaiwa_Bunpo_L03/K03_05/93.mp3
  - japanese: する
    english: to do (〜を)
    sound_file: Kaiwa_Bunpo_L03/K03_05/95.mp3
  - japanese: べんきょうする
    english: to study (〜を)
    kanji: 勉強する
    sound_file: Kaiwa_Bunpo_L03/K03_05/97.mp3
- tags:
  - Adjectives
  vocabulary:
  - japanese: いい
    english: good
    sound_file: Kaiwa_Bunpo_L03/K03_05/99.mp3
  - japanese: はやい
    english: early
    kanji: 早い
    sound_file: Kaiwa_Bunpo_L03/K03_05/101.mp3
- tags:
  - Adverbs
  vocabulary:
  - japanese: あまり + negative
    english: not much
    sound_file: Kaiwa_Bunpo_L03/K03_05/103.mp3
  - japanese: ぜんぜん + negative
    english: not at all
    kanji: 全然
    sound_file: Kaiwa_Bunpo_L03/K03_05/105.mp3
  - japanese: たいてい
    english: usually
    sound_file: Kaiwa_Bunpo_L03/K03_05/107.mp3
  - japanese: ちょっと
    english: a little
    sound_file: Kaiwa_Bunpo_L03/K03_05/109.mp3
  - japanese: ときどき
    english: sometimes
    kanji: 時々
    sound_file: Kaiwa_Bunpo_L03/K03_05/111.mp3
  - japanese: よく
    english: often; much
    sound_file: Kaiwa_Bunpo_L03/K03_05/113.mp3
- tags:
  - Expressions
  vocabulary:
  - japanese: そうですね
    english: That's right.; Let me see.
    sound_file: Kaiwa_Bunpo_L03/K03_05/115.mp3
  - japanese: でも
    english: but
    sound_file: Kaiwa_Bunpo_L03/K03_05/117.mp3
  - japanese: どうですか
    english: How about ...?; How is ...?
    sound_file: Kaiwa_Bunpo_L03/K03_05/119.mp3
  - japanese: ええ
    english: yes (casual)
    sound_file: Kaiwa_Bunpo_L03/K03_05/121.mp3
