tags:
- Genki_2
- Lesson_15
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: がいこくじん
    english: foreigner
    kanji: 外国人
    sound_file: Kaiwa_Bunpo_L15/K15_07/3.mp3
  - japanese: そば
    english: Soba; Japanese buckwheat noodle (also buckwheat itself)
    sound_file: Kaiwa_Bunpo_L15/K15_07/5.mp3
  - japanese: え
    english: painting; picture; drawing
    kanji: 絵
    sound_file: Kaiwa_Bunpo_L15/K15_07/7.mp3
  - japanese: ちず
    english: map
    kanji: 地図
    sound_file: Kaiwa_Bunpo_L15/K15_07/9.mp3
  - japanese: じしょ
    english: dictionary
    kanji: 辞書
    sound_file: Kaiwa_Bunpo_L15/K15_07/12.mp3
  - japanese: かぐ
    english: furniture
    kanji: 家具
    sound_file: Kaiwa_Bunpo_L15/K15_07/14.mp3
  - japanese: でんち
    english: battery
    kanji: 電池
    sound_file: Kaiwa_Bunpo_L15/K15_07/18.mp3
  - japanese: ジャケット
    english: jacket
    sound_file: Kaiwa_Bunpo_L15/K15_07/20.mp3
  - japanese: ペット
    english: pet
    sound_file: Kaiwa_Bunpo_L15/K15_07/22.mp3
  - japanese: わりびきけん
    english: discount coupon
    kanji: 割引券
    sound_file: Kaiwa_Bunpo_L15/K15_07/24.mp3
  - japanese: インターネット
    english: internet (informally ネット)
    sound_file: Kaiwa_Bunpo_L15/K15_07/26.mp3
  - japanese: じしん
    english: earthquake
    kanji: 地震
    sound_file: Kaiwa_Bunpo_L15/K15_07/28.mp3
  - japanese: ほけん
    english: insurance
    kanji: 保険
    sound_file: Kaiwa_Bunpo_L15/K15_07/30.mp3
  - japanese: ぜいきん
    english: tax
    kanji: 税金
    sound_file: Kaiwa_Bunpo_L15/K15_07/32.mp3
  - japanese: きょうしつ
    english: classroom
    kanji: 教室
    sound_file: Kaiwa_Bunpo_L15/K15_07/34.mp3
  - japanese: たてもの
    english: building
    kanji: 建物
    sound_file: Kaiwa_Bunpo_L15/K15_07/36.mp3
  - japanese: プール
    english: swimming pool
    sound_file: Kaiwa_Bunpo_L15/K15_07/38.mp3
  - japanese: えいがかん
    english: movie theater
    kanji: 映画館
    sound_file: Kaiwa_Bunpo_L15/K15_07/40.mp3
  - japanese: りょかん
    english: inn
    kanji: 旅館
    sound_file: Kaiwa_Bunpo_L15/K15_07/42.mp3
  - japanese: にわ
    english: garden
    kanji: 庭
    sound_file: Kaiwa_Bunpo_L15/K15_07/44.mp3
  - japanese: ボランティア
    english: volunteer
    sound_file: Kaiwa_Bunpo_L15/K15_07/46.mp3
  - japanese: かつどう
    english: activity
    kanji: 活動
    sound_file: Kaiwa_Bunpo_L15/K15_07/48.mp3
  - japanese: けいけん
    english: experience
    kanji: 経験
    sound_file: Kaiwa_Bunpo_L15/K15_07/50.mp3
  - japanese: しゅうかん
    english: custom
    kanji: 習慣
    sound_file: Kaiwa_Bunpo_L15/K15_07/52.mp3
  - japanese: しめきり
    english: deadline
    kanji: 締め切り
    sound_file: Kaiwa_Bunpo_L15/K15_07/54.mp3
  - japanese: よてい
    english: schedule; plan
    kanji: 予定
    sound_file: Kaiwa_Bunpo_L15/K15_07/56.mp3
  - japanese: そつぎょうしき
    english: graduation ceremony
    kanji: 卒業式
    sound_file: Kaiwa_Bunpo_L15/K15_07/58.mp3
  - japanese: けっこんしき
    english: wedding
    kanji: 結婚式
    sound_file: Kaiwa_Bunpo_L15/K15_07/60.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: うる
    english: to sell （〜を）
    kanji: 売る
    sound_file: Kaiwa_Bunpo_L15/K15_07/62.mp3
  - japanese: おろす
    english: to withdraw (money)　（〜を）
    kanji: 下ろす
    sound_file: Kaiwa_Bunpo_L15/K15_07/64.mp3
  - japanese: かく
    english: to draw; to paint　（〜を）
    kanji: 描く
    sound_file: Kaiwa_Bunpo_L15/K15_07/66.mp3
  - japanese: さがす
    english: to look for
    kanji: 探す
    sound_file: Kaiwa_Bunpo_L15/K15_07/68.mp3
  - japanese: さそう
    english: to invite
    kanji: 誘う
    sound_file: Kaiwa_Bunpo_L15/K15_07/70.mp3
  - japanese: しゃべる
    english: to chat
    kanji: 喋る(rare)
    sound_file: Kaiwa_Bunpo_L15/K15_07/72.mp3
  - japanese: つきあう
    english: (1) to date (someone) (personと); (2) to keep company (purpose に）
    kanji: 付き合う
    sound_file: Kaiwa_Bunpo_L15/K15_07/74.mp3
  - japanese: つく
    english: to arrive
    kanji: 着く
    sound_file: Kaiwa_Bunpo_L15/K15_07/76.mp3
  - japanese: ほけんにはいる
    english: to buy insurance
    kanji: 保険に入る
    sound_file: Kaiwa_Bunpo_L15/K15_07/78.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: きをつける
    english: to be cautious/careful(〜に)
    kanji: 気をつける
    sound_file: Kaiwa_Bunpo_L15/K15_07/80.mp3
  - japanese: しらべる
    english: to look into (matterを)
    kanji: 調べる
    sound_file: Kaiwa_Bunpo_L15/K15_07/82.mp3
  - japanese: みえる
    english: to be visible(〜が）
    kanji: 見える
    sound_file: Kaiwa_Bunpo_L15/K15_07/84.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: する
    english: to decide on (itemに)
    sound_file: Kaiwa_Bunpo_L15/K15_07/86.mp3
  - japanese: かんこうする
    english: sightseeing
    kanji: 観光する
    sound_file: Kaiwa_Bunpo_L15/K15_07/88.mp3
  - japanese: よやくする
    english: to reserve(〜を)
    kanji: 予約する
    sound_file: Kaiwa_Bunpo_L15/K15_07/90.mp3
  - japanese: さんかする
    english: to participate(~に)
    kanji: 参加する
    sound_file: Kaiwa_Bunpo_L15/K15_07/92.mp3
  - japanese: そつぎょうする
    english: to graduate (school/programを)
    kanji: 卒業する
    sound_file: Kaiwa_Bunpo_L15/K15_07/94.mp3
  - japanese: はっぴょうする
    english: to make a presentation; to make public
    kanji: 発表する
    sound_file: Kaiwa_Bunpo_L15/K15_07/96.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: 〜けど
    english: '...but;...'
    sound_file: Kaiwa_Bunpo_L15/K15_07/98.mp3
  - japanese: 〜め
    english: 〜-th
    kanji: 〜目
    sound_file: Kaiwa_Bunpo_L15/K15_07/100.mp3
  - japanese: いちにちめ
    english: first day
    kanji: 一日目
    sound_file: Kaiwa_Bunpo_L15/K15_07/102.mp3
  - japanese: いちにちじゅう
    english: all day long
    kanji: 一日中
    sound_file: Kaiwa_Bunpo_L15/K15_07/104.mp3
  - japanese: さいきん
    english: recently
    kanji: 最近
    sound_file: Kaiwa_Bunpo_L15/K15_07/106.mp3
  - japanese: もういちど
    english: one more time
    kanji: もう一度
    sound_file: Kaiwa_Bunpo_L15/K15_07/108.mp3
  - japanese: たのしみです
    english: cannot wait; look forward to it
    kanji: 楽しみです
    sound_file: Kaiwa_Bunpo_L15/K15_07/111.mp3
