tags:
- Genki_2
- Lesson_13
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: おとな
    english: adult
    kanji: 大人
    sound_file: Kaiwa_Bunpo_L13/K13_07/3.mp3
  - japanese: べんごし
    english: lawyer
    kanji: 弁護士
    sound_file: Kaiwa_Bunpo_L13/K13_07/5.mp3
  - japanese: わたくし
    english: I (formal)
    kanji: 私
    sound_file: Kaiwa_Bunpo_L13/K13_07/7.mp3
  - japanese: カレー
    english: curry
    sound_file: Kaiwa_Bunpo_L13/K13_07/9.mp3
  - japanese: こうちゃ
    english: black tea
    kanji: 紅茶
    sound_file: Kaiwa_Bunpo_L13/K13_07/11.mp3
  - japanese: きもの
    english: kimono; Japanese traditional dress
    kanji: 着物
    sound_file: Kaiwa_Bunpo_L13/K13_07/13.mp3
  - japanese: セーター
    english: sweater
    sound_file: Kaiwa_Bunpo_L13/K13_07/16.mp3
  - japanese: がっき
    english: musical instrument
    kanji: 楽器
    sound_file: Kaiwa_Bunpo_L13/K13_07/18.mp3
  - japanese: からて
    english: karate
    kanji: 空手
    sound_file: Kaiwa_Bunpo_L13/K13_07/20.mp3
  - japanese: ゴルフ
    english: golf
    sound_file: Kaiwa_Bunpo_L13/K13_07/22.mp3
  - japanese: バイク
    english: motorcycle
    sound_file: Kaiwa_Bunpo_L13/K13_07/24.mp3
  - japanese: ぞう
    english: elephant
    kanji: 象
    sound_file: Kaiwa_Bunpo_L13/K13_07/26.mp3
  - japanese: からだ
    english: body
    kanji: 体
    sound_file: Kaiwa_Bunpo_L13/K13_07/28.mp3
  - japanese: がいこくご
    english: foreign language
    kanji: 外国語
    sound_file: Kaiwa_Bunpo_L13/K13_07/30.mp3
  - japanese: ことば
    english: language (words)
    kanji: 言葉
    sound_file: Kaiwa_Bunpo_L13/K13_07/32.mp3
  - japanese: ぶんぽう
    english: grammar
    kanji: 文法
    sound_file: Kaiwa_Bunpo_L13/K13_07/34.mp3
  - japanese: アプリ
    english: application
    sound_file: Kaiwa_Bunpo_L13/K13_07/36.mp3
  - japanese: アパート
    english: apartment; smaller apartment building
    sound_file: Kaiwa_Bunpo_L13/K13_07/38.mp3
  - japanese: マンション
    english: larger apartment building; condominium
    sound_file: Kaiwa_Bunpo_L13/K13_07/41.mp3
  - japanese: くうこう
    english: airport
    kanji: 空港
    sound_file: Kaiwa_Bunpo_L13/K13_07/44.mp3
  - japanese: みせ
    english: shop; store
    kanji: 店
    sound_file: Kaiwa_Bunpo_L13/K13_07/46.mp3
  - japanese: ぶっか
    english: consumer prices
    kanji: 物価
    sound_file: Kaiwa_Bunpo_L13/K13_07/49.mp3
  - japanese: こうこく
    english: advertisement
    kanji: 広告
    sound_file: Kaiwa_Bunpo_L13/K13_07/51.mp3
  - japanese: ぼしゅう
    english: recruitment
    kanji: 募集
    sound_file: Kaiwa_Bunpo_L13/K13_07/53.mp3
  - japanese: やくそく
    english: promise; appointment
    kanji: 約束
    sound_file: Kaiwa_Bunpo_L13/K13_07/55.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: うれしい
    english: glad
    sound_file: Kaiwa_Bunpo_L13/K13_07/58.mp3
  - japanese: かなしい
    english: sad
    kanji: 悲しい
    sound_file: Kaiwa_Bunpo_L13/K13_07/60.mp3
  - japanese: きびしい
    english: strict
    kanji: 厳しい
    sound_file: Kaiwa_Bunpo_L13/K13_07/62.mp3
  - japanese: きぶんがわるい
    english: to feel sick
    kanji: 気分が悪い
    sound_file: Kaiwa_Bunpo_L13/K13_07/64.mp3
  - japanese: からい
    english: hot and spicy; salty
    kanji: 辛い
    sound_file: Kaiwa_Bunpo_L13/K13_07/66.mp3
  - japanese: すごい
    english: incredible; awesome
    sound_file: Kaiwa_Bunpo_L13/K13_07/69.mp3
  - japanese: ちかい
    english: close; near
    kanji: 近い
    sound_file: Kaiwa_Bunpo_L13/K13_07/72.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: いろいろ(な)
    english: various; different kinds of
    kanji: 色々
    sound_file: Kaiwa_Bunpo_L13/K13_07/76.mp3
  - japanese: しあわせ(な)
    english: happy (lasting happiness)
    kanji: 幸せ
    sound_file: Kaiwa_Bunpo_L13/K13_07/79.mp3
  - japanese: だめ(な)
    english: no good
    sound_file: Kaiwa_Bunpo_L13/K13_07/81.mp3
- tags:
  - U-verbs
  vocabulary:
  - japanese: あむ
    english: to knit (~を)
    kanji: 編む
    sound_file: Kaiwa_Bunpo_L13/K13_07/84.mp3
  - japanese: がんばる
    english: to do one's best; to try hard
    kanji: 頑張る
    sound_file: Kaiwa_Bunpo_L13/K13_07/86.mp3
  - japanese: なく
    english: to cry
    kanji: 泣く
    sound_file: Kaiwa_Bunpo_L13/K13_07/89.mp3
  - japanese: みがく
    english: to brush (teeth); to polish (~を)
    kanji: 磨く
    sound_file: Kaiwa_Bunpo_L13/K13_07/91.mp3
  - japanese: やくそくをまもる
    english: to keep a promise (lit.”protect a promise”)
    kanji: 約束を守る
    sound_file: Kaiwa_Bunpo_L13/K13_07/94.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: かんどうする
    english: to be moved; touched (by …) (~に)
    kanji: 感動する
    sound_file: Kaiwa_Bunpo_L13/K13_07/97.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: 〜かい
    english: '...times'
    kanji: 〜回
    sound_file: Kaiwa_Bunpo_L13/K13_07/101.mp3
  - japanese: 〜キロ
    english: '...kilometers; ...kilograms'
    sound_file: Kaiwa_Bunpo_L13/K13_07/103.mp3
  - japanese: ぜんぶ
    english: all
    kanji: 全部
    sound_file: Kaiwa_Bunpo_L13/K13_07/106.mp3
  - japanese: 〜ともうします
    english: my name is ~
    kanji: 〜と申します
    sound_file: Kaiwa_Bunpo_L13/K13_07/108.mp3
  - japanese: とくに
    english: especially
    kanji: 特に
    sound_file: Kaiwa_Bunpo_L13/K13_07/110.mp3
- tags:
  - Numbers
  vocabulary:
  - japanese: いちにち
    english: one day
    kanji: 一日
    sound_file: Kaiwa_Bunpo_L13/K13_07/113.mp3
  - japanese: ふつか
    english: two days
    kanji: 二日
    sound_file: Kaiwa_Bunpo_L13/K13_07/115.mp3
  - japanese: みっか
    english: three days
    kanji: 三日
    sound_file: Kaiwa_Bunpo_L13/K13_07/117.mp3
  - japanese: よっか
    english: four days
    kanji: 四日
    sound_file: Kaiwa_Bunpo_L13/K13_07/119.mp3
  - japanese: いつか
    english: five days
    kanji: 五日
    sound_file: Kaiwa_Bunpo_L13/K13_07/121.mp3
  - japanese: むいか
    english: six days
    kanji: 六日
    sound_file: Kaiwa_Bunpo_L13/K13_07/123.mp3
  - japanese: なのか
    english: seven days
    kanji: 七日
    sound_file: Kaiwa_Bunpo_L13/K13_07/125.mp3
  - japanese: ようか
    english: eight days
    kanji: 八日
    sound_file: Kaiwa_Bunpo_L13/K13_07/127.mp3
  - japanese: ここのか
    english: nine days
    kanji: 九日
    sound_file: Kaiwa_Bunpo_L13/K13_07/129.mp3
  - japanese: とおか
    english: ten days
    kanji: 十日
    sound_file: Kaiwa_Bunpo_L13/K13_07/131.mp3
