tags:
- Genki_2
- Lesson_17
- 01_Vocabulary
vocabulary:
- tags:
  - Nouns
  vocabulary:
  - japanese: あかちゃん
    english: baby
    kanji: 赤ちゃん
    sound_file: Kaiwa_Bunpo_L17/K17_05/3.mp3
  - japanese: おきゃくさん
    english: guest; vistor; client; customer
    kanji: お客さん
    sound_file: Kaiwa_Bunpo_L17/K17_05/5.mp3
  - japanese: しゅしょう
    english: prime minister
    kanji: 首相
    sound_file: Kaiwa_Bunpo_L17/K17_05/7.mp3
  - japanese: サラリーマン
    english: salaryman; office worker
    sound_file: Kaiwa_Bunpo_L17/K17_05/9.mp3
  - japanese: きゅうりょう
    english: salary
    kanji: 給料
    sound_file: Kaiwa_Bunpo_L17/K17_05/14.mp3
  - japanese: ざんぎょう
    english: overtime work
    kanji: 残業
    sound_file: Kaiwa_Bunpo_L17/K17_05/16.mp3
  - japanese: パンダ
    english: panda
    sound_file: Kaiwa_Bunpo_L17/K17_05/18.mp3
  - japanese: コンタクト（レンズ）
    english: contact lenses
    sound_file: Kaiwa_Bunpo_L17/K17_05/20.mp3
  - japanese: ひげ
    english: beard
    kanji: 髭(rare)
    sound_file: Kaiwa_Bunpo_L17/K17_05/23.mp3
  - japanese: ブーツ
    english: boots
    sound_file: Kaiwa_Bunpo_L17/K17_05/25.mp3
  - japanese: かぎ
    english: lock; key
    kanji: 鍵
    sound_file: Kaiwa_Bunpo_L17/K17_05/27.mp3
  - japanese: たからくじ
    english: lottery
    kanji: 宝くじ
    sound_file: Kaiwa_Bunpo_L17/K17_05/29.mp3
  - japanese: かみ
    english: paper
    kanji: 紙
    sound_file: Kaiwa_Bunpo_L17/K17_05/31.mp3
  - japanese: スプーン
    english: spoon
    sound_file: Kaiwa_Bunpo_L17/K17_05/33.mp3
  - japanese: おゆ
    english: hot water
    kanji: お湯
    sound_file: Kaiwa_Bunpo_L17/K17_05/35.mp3
  - japanese: でんしレンジ
    english: microwave oven
    kanji: 電子レンジ
    sound_file: Kaiwa_Bunpo_L17/K17_05/37.mp3
  - japanese: ヒーター
    english: heater
    sound_file: Kaiwa_Bunpo_L17/K17_05/39.mp3
  - japanese: ニュース
    english: news
    sound_file: Kaiwa_Bunpo_L17/K17_05/41.mp3
  - japanese: かじ
    english: fire
    kanji: 火事
    sound_file: Kaiwa_Bunpo_L17/K17_05/43.mp3
  - japanese: りょこうがいしゃ
    english: travel agency
    kanji: 旅行会社
    sound_file: Kaiwa_Bunpo_L17/K17_05/45.mp3
  - japanese: ショッピングモール
    english: shopping mall
    sound_file: Kaiwa_Bunpo_L17/K17_05/47.mp3
  - japanese: りょう
    english: dormitory
    kanji: 寮
    sound_file: Kaiwa_Bunpo_L17/K17_05/49.mp3
  - japanese: ちがい
    english: difference
    kanji: 違い
    sound_file: Kaiwa_Bunpo_L17/K17_05/52.mp3
  - japanese: ひみつ
    english: secret
    kanji: 秘密
    sound_file: Kaiwa_Bunpo_L17/K17_05/54.mp3
  - japanese: じゅんび
    english: preparation
    kanji: 準備
    sound_file: Kaiwa_Bunpo_L17/K17_05/56.mp3
  - japanese: じぶん
    english: oneself
    kanji: 自分
    sound_file: Kaiwa_Bunpo_L17/K17_05/58.mp3
- tags:
  - い-adjectives
  vocabulary:
  - japanese: あぶない
    english: dangerous
    kanji: 危ない
    sound_file: Kaiwa_Bunpo_L17/K17_05/60.mp3
  - japanese: うらやましい
    english: envious
    kanji: 羨ましい
    sound_file: Kaiwa_Bunpo_L17/K17_05/62.mp3
  - japanese: すくない
    english: a little; a few
    kanji: 少ない
    sound_file: Kaiwa_Bunpo_L17/K17_05/64.mp3
  - japanese: つごうがわるい
    english: inconvenient; to have a scheduling conflict
    kanji: 都合が悪い
    sound_file: Kaiwa_Bunpo_L17/K17_05/66.mp3
  - japanese: つよい
    english: strong
    kanji: 強い
    sound_file: Kaiwa_Bunpo_L17/K17_05/68.mp3
- tags:
  - な-adjectives
  vocabulary:
  - japanese: さいあく(な)
    english: the worst
    kanji: 最悪
    sound_file: Kaiwa_Bunpo_L17/K17_05/70.mp3
- tags:
  - U_verbs
  vocabulary:
  - japanese: えらぶ
    english: to choose; to select (～を)
    kanji: 選ぶ
    sound_file: Kaiwa_Bunpo_L17/K17_05/72.mp3
  - japanese: おゆをわかす
    english: to boil water
    kanji: お湯を沸かす
    sound_file: Kaiwa_Bunpo_L17/K17_05/74.mp3
  - japanese: かみをとかす
    english: to comb one's hair
    kanji: 髪をとかす
    sound_file: Kaiwa_Bunpo_L17/K17_05/76.mp3
  - japanese: ひげをそる
    english: to shave one's beard
    kanji: 髭を剃る(rare)
    sound_file: Kaiwa_Bunpo_L17/K17_05/78.mp3
  - japanese: ぬぐ
    english: to take off (clothes) (～を)
    kanji: 脱ぐ
    sound_file: Kaiwa_Bunpo_L17/K17_05/80.mp3
  - japanese: こむ
    english: to get crowded (～が)
    kanji: 混む
    sound_file: Kaiwa_Bunpo_L17/K17_05/82.mp3
  - japanese: たからくじにあたる
    english: to win a lottery
    kanji: 宝くじに当たる
    sound_file: Kaiwa_Bunpo_L17/K17_05/84.mp3
- tags:
  - Ru-verbs
  vocabulary:
  - japanese: いれる
    english: to make tea, coffee, etc. (～を)
    kanji: 入れる
    sound_file: Kaiwa_Bunpo_L17/K17_05/86.mp3
  - japanese: うまれる
    english: to be born (～が)
    kanji: 生まれる
    sound_file: Kaiwa_Bunpo_L17/K17_05/88.mp3
  - japanese: かぎをかける
    english: to lock (～に)
    kanji: 鍵をかける
    sound_file: Kaiwa_Bunpo_L17/K17_05/90.mp3
  - japanese: たりる
    english: to be sufficient; to be enough (～が)
    kanji: 足りる
    sound_file: Kaiwa_Bunpo_L17/K17_05/92.mp3
  - japanese: なれる
    english: to get used to… (～に)
    kanji: 慣れる
    sound_file: Kaiwa_Bunpo_L17/K17_05/94.mp3
- tags:
  - Irregular_Verbs
  vocabulary:
  - japanese: おいのりする
    english: to pray (～に)
    kanji: お祈りする
    sound_file: Kaiwa_Bunpo_L17/K17_05/96.mp3
  - japanese: けしょうする
    english: to put makeup on
    kanji: 化粧する
    sound_file: Kaiwa_Bunpo_L17/K17_05/98.mp3
  - japanese: しゅうしょくする
    english: to get a full-time job (at) (companyに)
    kanji: 就職する
    sound_file: Kaiwa_Bunpo_L17/K17_05/100.mp3
  - japanese: りこんする
    english: to get a divorce (personと)
    kanji: 離婚する
    sound_file: Kaiwa_Bunpo_L17/K17_05/102.mp3
  - japanese: する
    english: to wear small items (necktie, watch, etc.) (～を)
    kanji: （e.g. ネクタイをする)
    sound_file: Kaiwa_Bunpo_L17/K17_05/104.mp3
- tags:
  - Adverbs_and_Other_Expressions
  vocabulary:
  - japanese: ずいぶん
    english: very
    kanji: 随分(rare)
    sound_file: Kaiwa_Bunpo_L17/K17_05/106.mp3
  - japanese: たとえば
    english: for example
    kanji: 例えば
    sound_file: Kaiwa_Bunpo_L17/K17_05/108.mp3
  - japanese: ～にくらべて
    english: compared with…
    kanji: ～に比べて
    sound_file: Kaiwa_Bunpo_L17/K17_05/110.mp3
  - japanese: ～によると
    english: according to…
    sound_file: Kaiwa_Bunpo_L17/K17_05/113.mp3
  - japanese: まえ
    english: before…
    kanji: 前
    sound_file: Kaiwa_Bunpo_L17/K17_05/115.mp3
  - japanese: やっぱり
    english: after all
    kanji: 矢っ張り(rare)
    sound_file: Kaiwa_Bunpo_L17/K17_05/117.mp3
  - japanese: ～かな（あ）
    english: I wonder…(casual)
    sound_file: Kaiwa_Bunpo_L17/K17_05/119.mp3
  - japanese: そうか
    english: I see.(casual)
    kanji: 然うか(rare)
    sound_file: Kaiwa_Bunpo_L17/K17_05/121.mp3
  - japanese: おめでとうございます
    english: Congratulations!
    kanji: お目出度う御座います(rare)
    sound_file: Kaiwa_Bunpo_L17/K17_05/123.mp3
