tags:
- Genki_1
- Lesson_1
- 02_Additional_Vocabulary
vocabulary:
- tags:
  - Countries
  vocabulary:
  - japanese: イギリス
    english: Britain
    sound_file: Kaiwa_Bunpo_L01/K01_07/2.mp3
  - japanese: オーストラリア
    english: Australia
    sound_file: Kaiwa_Bunpo_L01/K01_07/4.mp3
  - japanese: かんこく
    english: Korea
    kanji: 韓国
    sound_file: Kaiwa_Bunpo_L01/K01_07/6.mp3
  - japanese: カナダ
    english: Canada
    sound_file: Kaiwa_Bunpo_L01/K01_07/8.mp3
  - japanese: ちゅうごく
    english: China
    kanji: 中国
    sound_file: Kaiwa_Bunpo_L01/K01_07/10.mp3
  - japanese: インド
    english: India
    sound_file: Kaiwa_Bunpo_L01/K01_07/12.mp3
  - japanese: エジプト
    english: Egypt
    sound_file: Kaiwa_Bunpo_L01/K01_07/14.mp3
  - japanese: フィリピン
    english: Philippines
    sound_file: Kaiwa_Bunpo_L01/K01_07/16.mp3
- tags:
  - Majors
  vocabulary:
  - japanese: アジアけんきゅう
    english: Asian studies
    kanji: アジア研究
    sound_file: Kaiwa_Bunpo_L01/K01_07/18.mp3
  - japanese: けいざい
    english: economics
    sound_file: Kaiwa_Bunpo_L01/K01_07/20.mp3
  - japanese: こうがく
    english: engineering
    sound_file: Kaiwa_Bunpo_L01/K01_07/22.mp3
  - japanese: こくさいかんけい
    english: international relations
    kanji: 国際関係
    sound_file: Kaiwa_Bunpo_L01/K01_07/24.mp3
  - japanese: コンピューター
    english: computer
    sound_file: Kaiwa_Bunpo_L01/K01_07/26.mp3
  - japanese: せいじ
    english: politics
    kanji: 政治
    sound_file: Kaiwa_Bunpo_L01/K01_07/28.mp3
  - japanese: せいぶつがく
    english: biology
    sound_file: Kaiwa_Bunpo_L01/K01_07/30.mp3
  - japanese: ビジネス
    english: business
    sound_file: Kaiwa_Bunpo_L01/K01_07/32.mp3
  - japanese: ぶんがく
    english: literature
    kanji: 文学
    sound_file: Kaiwa_Bunpo_L01/K01_07/35.mp3
  - japanese: れきし
    english: history
    kanji: 歴史
    sound_file: Kaiwa_Bunpo_L01/K01_07/37.mp3
- tags:
  - Occupations
  vocabulary:
  - japanese: いしゃ
    english: doctor
    kanji: 医者
    sound_file: Kaiwa_Bunpo_L01/K01_07/39.mp3
  - japanese: かいしゃいん
    english: office worker
    kanji: 会社員
    sound_file: Kaiwa_Bunpo_L01/K01_07/41.mp3
  - japanese: かんごし
    english: nurse
    kanji: 看護師
    sound_file: Kaiwa_Bunpo_L01/K01_07/43.mp3
  - japanese: こうこうせい
    english: high school student
    kanji: 高校生
    sound_file: Kaiwa_Bunpo_L01/K01_07/45.mp3
  - japanese: しゅふ
    english: housewife
    kanji: 主婦
    sound_file: Kaiwa_Bunpo_L01/K01_07/47.mp3
  - japanese: だいがくいんせい
    english: graduate student
    kanji: 大学院生
    sound_file: Kaiwa_Bunpo_L01/K01_07/49.mp3
  - japanese: べんごし
    english: lawyer
    kanji: 弁護士
    sound_file: Kaiwa_Bunpo_L01/K01_07/51.mp3
- tags:
  - Family
  vocabulary:
  - japanese: おかあさん
    english: mother
    kanji: お母さん
    sound_file: Kaiwa_Bunpo_L01/K01_07/53.mp3
  - japanese: おとうさん
    english: father
    kanji: お父さん
    sound_file: Kaiwa_Bunpo_L01/K01_07/55.mp3
  - japanese: おねえさん
    english: older sister
    kanji: お姉さん
    sound_file: Kaiwa_Bunpo_L01/K01_07/57.mp3
  - japanese: おにいさん
    english: older brother
    kanji: お兄さん
    sound_file: Kaiwa_Bunpo_L01/K01_07/59.mp3
  - japanese: いもうと
    english: younger sister
    kanji: 妹
    sound_file: Kaiwa_Bunpo_L01/K01_07/61.mp3
  - japanese: おとうと
    english: younger brother
    kanji: 弟
    sound_file: Kaiwa_Bunpo_L01/K01_07/63.mp3
