tags:
- Genki_1
- Lesson_1
- 04_Years_Old
vocabulary:
- tags:
  - years_old
  vocabulary:
  - japanese: いっさい*
    english: one year old
    kanji: 一歳
  - japanese: にさい
    english: two years old
    kanji: 二歳
  - japanese: さんさい
    english: three years old
    kanji: 三歳
  - japanese: よんさい
    english: four years old
    kanji: 四歳
  - japanese: ごさい
    english: five years old
    kanji: 五歳
  - japanese: ろくさい
    english: six years old
    kanji: 六歳
  - japanese: ななさい
    english: seven years old
    kanji: 七歳
  - japanese: はっさい*
    english: eight years old
    kanji: 八歳
  - japanese: きゅうさい
    english: nine years old
    kanji: 九歳
  - japanese: じゅっさい*
    english: ten years old
    kanji: 十歳
  - japanese: じゅういっさい
    english: eleven years old
    kanji: 十一歳
  - japanese: はたち*／にじゅっさい
    english: 20 years old
    kanji: 二十歳
  - japanese: にじゅういっさい
    english: 21 years old
    kanji: 二十一歳
  - japanese: さんじゅうごさい
    english: 35 years old
    kanji: 三十五歳
  - japanese: よんじゅっさい
    english: 40 years old
    kanji: 四十歳
  - japanese: 〜さい
    english: '... years old'
    kanji: 〜歳
