tags:
- Genki_1
- Lesson_11
- 02_Additional_Vocabulary
vocabulary:
- tags:
  - Occupations
  vocabulary:
  - japanese: しょくぎょう
    english: Occupations
    kanji: 職業
    sound_file: Kaiwa_Bunpo_L11/K11_09/1.mp3
  - japanese: さっか
    english: writer
    kanji: 作家
    sound_file: Kaiwa_Bunpo_L11/K11_09/3.mp3
  - japanese: ジャーナリスト
    english: journalist
    sound_file: Kaiwa_Bunpo_L11/K11_09/5.mp3
  - japanese: けいさつかん
    english: police officer
    kanji: 警察官
    sound_file: Kaiwa_Bunpo_L11/K11_09/7.mp3
  - japanese: しょうぼうし
    english: firefighter
    kanji: 消防士
    sound_file: Kaiwa_Bunpo_L11/K11_09/9.mp3
  - japanese: きょうし
    english: schoolteacher
    kanji: 教師
    sound_file: Kaiwa_Bunpo_L11/K11_09/11.mp3
  - japanese: けんきゅうしゃ
    english: researcher
    kanji: 研究者
    sound_file: Kaiwa_Bunpo_L11/K11_09/13.mp3
  - japanese: うちゅうひこうし
    english: astronaut
    kanji: 宇宙飛行士
    sound_file: Kaiwa_Bunpo_L11/K11_09/15.mp3
  - japanese: スポーツせんしゅ
    english: athlete
    kanji: スポーツ選手
    sound_file: Kaiwa_Bunpo_L11/K11_09/17.mp3
  - japanese: だいとうりょう
    english: president of a country
    kanji: 大統領
    sound_file: Kaiwa_Bunpo_L11/K11_09/19.mp3
  - japanese: はいゆう
    english: actor; actress
    kanji: 俳優
    sound_file: Kaiwa_Bunpo_L11/K11_09/21.mp3
  - japanese: かんごし
    english: nurse
    kanji: 看護師
    sound_file: Kaiwa_Bunpo_L11/K11_09/24.mp3
  - japanese: シェフ
    english: chef
    sound_file: Kaiwa_Bunpo_L11/K11_09/26.mp3
  - japanese: まんがか
    english: cartoonist
    kanji: 漫画家
    sound_file: Kaiwa_Bunpo_L11/K11_09/28.mp3
