tags:
- Genki_1
- Lesson_11
- 03_Japanese_Class
vocabulary:
- tags:
  - Useful_Expressions
  vocabulary:
  - japanese: どちらでもいいです。
    english: Both are fine.
  - japanese: おなじです。
    english: Same thing.
    kanji: 同じです。
  - japanese: だいたいおなじです。
    english: More or less the same.
    kanji: だいたい同じです。
  - japanese: ちょっとちがいます。
    english: A little different.
    kanji: ちょっと違います。
  - japanese: つかえません。
    english: Can't use it.
    kanji: 使えません
  - japanese: だめです。
    english: No good.
  - japanese: てをあげてください。
    english: Raise your hand.
    kanji: 手をあげてください。
  - japanese: よんできてください。
    english: Read it before coming to class.
    kanji: 読んできてください。
  - japanese: しゅくだいをだしてください。
    english: Hand in the homework.
    kanji: 宿題を出してください。
  - japanese: １０ページをひらいてください。
    english: Open the book to page 10.
    kanji: １０ページを開いてください。
  - japanese: きょうかしょをとじてください。
    english: Close the textbook.
    kanji: 教科書を閉じてください。
  - japanese: となりのひとにきいてください。
    english: Ask the person sitting next to you.
    kanji: となりの人に聞いてください。
  - japanese: やめてください。
    english: Please stop.
  - japanese: きょうはこれでおわります。
    english: That's it for today.
    kanji: 今日はこれで終わります。
  - japanese: しめきり
    english: deadline
  - japanese: れんしゅう
    english: exercise
    kanji: 練習
  - japanese: いみ
    english: meaning
    kanji: 意味
  - japanese: はつおん
    english: pronunciation
    kanji: 発音
  - japanese: ぶんぽう
    english: grammar
    kanji: 文法
  - japanese: しつもん
    english: question
    kanji: 質問
  - japanese: こたえ
    english: answer
    kanji: 答
  - japanese: れい
    english: example
    kanji: 例
  - japanese: かっこ
    english: ( ) (parentheses)
  - japanese: まる
    english: ○ (correct)
  - japanese: ばつ
    english: ☓ (wrong)
  - japanese: くだけたいいかた
    english: colloquial expression
    kanji: くだけた言い方
  - japanese: かたいいいかた
    english: bookish expression
    kanji: かたい言い方
  - japanese: ていねいないいかた
    english: polite expression
    kanji: ていねいな言い方
  - japanese: ほうげん
    english: dialect
    kanji: 方言
  - japanese: きょうつうご
    english: common language
    kanji: 共通語
  - japanese: たとえば
    english: for example
  - japanese: ほかに
    english: anything else
  - japanese: 〜ばん
    english: number ...
  - japanese: 〜ぎょうめ
    english: line number ...
    kanji: 〜行目
  - japanese: ふたりずつ
    english: two people each
    kanji: 二人ずつ
